sudo: required

services:
  - docker
  
env:
  global:
    - secure: "ZyVa1CRHccxHzh2yXMHKNviYyINnW6dWFiUO5EadjV0W50UYyUjEgZ5yubDugbgKtVa8Ye1ZXFwoQCRLBxZKPaV/q/IM+n/ft4C00M+GXgkehdxUbf+xxKb9gq33MnTMF5Ym7eEihv7KvPPOepH0chEFqFPlSlRHQPXuwF5yH6x0NtQp48kCCNeFuFYiSxNUHMrPr/TuXiw6re1gH3Cx8oOy3otLWh0/6UeXXpbKjhVRdS2d8CSVcD6IQm9NhqiZDY95/Gl50nsfMsSwwPT0Chx2gAXFwQGVrIj4HeDuiq0AWXHXZpRLXovSyJfZAxbRx2LCEuixGoB6DD/KAftehykzey35SG0UsyB3KUeJo8NNvaUFzq27Y36xA94qdBgvvdrkU/mSJukBtciaCE36MD+yo0CXt+17UHkAqmCh35WJlm6yxvKSmwhyHa9ERFg/KSJdAWhZ+clUVonq70IVHEw9D+oi2RHg5dQiLoPk3tEfS7yOCumYLweE8obqez/oGs25EaE0bHPXGHsO4gd0tYs+urBbmwj4P5YiYAMzR5BK8iHsCKLJ6AKC5xcIyz7y5jAEb8nibJAflXGGJUd0yqq9b8b2QpU0ng6CEo9h90/V2QfX8p113YhWHJX1CYvAjhbnuxIW7S24pT9GmUSBrz4/o1out+yyqEU5XdBsd9g=" 
     
