sudo: required

services:
  - docker
  
env:
  global:
    - secure: "ZyVa1CRHccxHzh2yXMHKNviYyINnW6dWFiUO5EadjV0W50UYyUjEgZ5yubDugbgKtVa8Ye1ZXFwoQCRLBxZKPaV/q/IM+n/ft4C00M+GXgkehdxUbf+xxKb9gq33MnTMF5Ym7eEihv7KvPPOepH0chEFqFPlSlRHQPXuwF5yH6x0NtQp48kCCNeFuFYiSxNUHMrPr/TuXiw6re1gH3Cx8oOy3otLWh0/6UeXXpbKjhVRdS2d8CSVcD6IQm9NhqiZDY95/Gl50nsfMsSwwPT0Chx2gAXFwQGVrIj4HeDuiq0AWXHXZpRLXovSyJfZAxbRx2LCEuixGoB6DD/KAftehykzey35SG0UsyB3KUeJo8NNvaUFzq27Y36xA94qdBgvvdrkU/mSJukBtciaCE36MD+yo0CXt+17UHkAqmCh35WJlm6yxvKSmwhyHa9ERFg/KSJdAWhZ+clUVonq70IVHEw9D+oi2RHg5dQiLoPk3tEfS7yOCumYLweE8obqez/oGs25EaE0bHPXGHsO4gd0tYs+urBbmwj4P5YiYAMzR5BK8iHsCKLJ6AKC5xcIyz7y5jAEb8nibJAflXGGJUd0yqq9b8b2QpU0ng6CEo9h90/V2QfX8p113YhWHJX1CYvAjhbnuxIW7S24pT9GmUSBrz4/o1out+yyqEU5XdBsd9g=" 
    - secure: "RhqyXAIiD05FnoeqTikSeb7k5JcvcMcJ8kxwIWK0iOUeHUyDv2Iw6H8WncSGqFVGpc86yPul3TxStWrhnheZh9c4yEGhZbhcp1nGE8J/jMUvLWCQX6jf02fnZoOIPpusYBb8gE/MFXPLTjYP58GsMN1FYjXtnKKWXL/5Z5tWjRiD2h2N6DsH4+BRSZcKrPOQqmpWadjlSzXgUYujNYg5Erpvvm6ihvtjPRrhAzpJnMxW2pJo6VynFns2LtS5twrQLthXrF12uITmI967vD30NIaYeB8bvXPh9Ka71QG9boigEPVcFQzd4ZRS5Uaa+zi/vtHpieilR25T992+oIXdVYNIJETr7uqKKYKveaXzqqk/STtQqoXiJ1OG4aBGExxnZ/oKQi1I06YOdvY4AAFQ7h03/MmqUwF70XPhYkbKxOeZHo51PIRDi97C0gwOtfhGLU5ppINQ37mWg5ay2GokZw13gixIUd9XWSEiyAIU4rnYOYkWxNp6C0PEEjIKfESfbMpVievI+DxEVcaJIN6tYdDT3SsAAeeQ1PlCcEDjvuG5qWY0RceAlecfkVfHVC1lqWeIoIifvZigQIG8RKKzcvaBRZdfMldp5DJJQZbUNGUknhm6+soqClU8SO52bKTtiKuCD/eh74Sk4txmivc0CPrBxJI4HaljZtAdw+VKx7U="
    - COMMIT=${TRAVIS_COMMIT::8}
    
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=500061070/travis-ci
  - export TAG=`if [ "$TRAVIS_BRANCH" == "main" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
